---
title: "p8105_hw2_SY3352"
author: "Su Yan"
date: "2025-10-01"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
```

## Problem 1
```{r}
pols_df = read_csv("data/pols-month.csv") |> 
  separate(mon, into = c("year","month","day"), sep = "-") |> 
  mutate(year = as.integer(year), month = as.integer(month)) |> 
  mutate(month = month.name[month]) |> 
  mutate(president = if_else(prez_gop == 1, "gop","dem")) |> 
  select(-prez_dem, -prez_gop)
```

```{r}
snp_df = read_csv("data/snp.csv") |> 
  mutate(date = mdy(date)) |> 
  mutate(year = year(date), month = month(date), day = day(date)) |> 
  mutate(month = month.name[month]) |> 
  select(-date) |> 
  relocate(year, month) |> 
  arrange(year, match(month, month.name))
```

```{r}
unemp_df = read_csv("data/unemployment.csv") |> 
  pivot_longer(cols = Jan:Dec,
               names_to = "month",
               values_to = "unemployment_rate") |> 
  mutate(month = recode(month,
                        Jan = "January", Feb = "February", Mar = "March",
                        Apr = "April", May = "May", Jun = "June",
                        Jul = "July", Aug = "August", Sep = "September",
                        Oct = "October", Nov = "November", Dec = "December")) 
```

