p8105_hw2_SY3352
================
Su Yan
2025-10-01

## Problem 1

``` r
pols_df = read_csv("data/pols-month.csv") |> 
  separate(mon, into = c("year","month","day"), sep = "-") |> 
  mutate(year = as.integer(year), month = as.integer(month)) |> 
  mutate(month = month.name[month]) |> 
  mutate(president = if_else(prez_gop == 1, "gop","dem")) |> 
  select(-prez_dem, -prez_gop,-day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_df = read_csv("data/snp.csv") |> 
  mutate(date = mdy(date)) |> 
  mutate(year = year(date), month = month(date), day = day(date)) |> 
  mutate(year = as.integer(year), month = month.name[month]) |> 
  mutate(year = if_else(year > 2024, year - 100, year)) |> 
  select(-date, -day) |> 
  relocate(year, month) |> 
  arrange(year, match(month, month.name))
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemp_df = read_csv("data/unemployment.csv") |> 
  pivot_longer(cols = Jan:Dec,
               names_to = "month",
               values_to = "unemployment_rate") |> 
  mutate(month = recode(month,
                        Jan = "January", Feb = "February", 
                        Mar = "March", Apr = "April", 
                        May = "May", Jun = "June",
                        Jul = "July", Aug = "August", 
                        Sep = "September", Oct = "October",
                        Nov = "November", Dec = "December")) |> 
  rename(year = Year) 
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
merge_df = pols_df |> 
  left_join(snp_df, by = c("year","month")) |> 
  left_join(unemp_df, by = c("year","month"))
```

The `pols_df` data set contains data from 1947 to 2015 of number of
politicians(including the president) in each political party in the US
by month. The `snp_df` contains data of closing values of the S&P stock
index from 1950 to 2015 by month. The `unemp_df` data set contains data
of unemployment rate from 1948 to 2015 by month. The merged `merge_df`
data set has 822 rows and 11 columns of data, which covered 1947 to 2015
of political party, S&P index closing value and employment information.
Some of the key variables in **`merge_df`** are `year` `month`
`president` `closing` and `unemployment_rate`.

## Problem 2

``` r
mtw_df = read_excel("data/202509 Trash Wheel Collection Data.xlsx",
                    sheet = "Mr. Trash Wheel",
                    skip = 1) |> 
  janitor::clean_names() |> 
  filter(!(dumpster == "na")) |> 
  mutate(sports_balls = as.integer(round(sports_balls))) |> 
  select(-x15, -x16)
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
ptw_df = read_excel("data/202509 Trash Wheel Collection Data.xlsx",
                    sheet = "Professor Trash Wheel",
                    skip = 1) |> 
  janitor::clean_names() |> 
  filter(!(dumpster == "na")) 
```

``` r
gtw_df = read_excel("data/202509 Trash Wheel Collection Data.xlsx",
                    sheet = "Gwynns Falls Trash Wheel",
                    skip = 1) |> 
  janitor::clean_names() |> 
  filter(!(dumpster == "na")) 
```

``` r
mtw_df = mutate(mtw_df, 
                wheel_name = "Mr. Trash Wheel", 
                year = as.integer(year))
ptw_df = mutate(ptw_df, 
                wheel_name = "Professor Trash Wheel", 
                year = as.integer(year))
gtw_df = mutate(gtw_df, 
                wheel_name = "Gwynns Falls Trash Wheel", 
                year = as.integer(year))
combined_df = bind_rows(mtw_df, ptw_df, gtw_df) 
```

By combining the data from the three data sheets, we get the
`combined_df` data set, which has 1188 rows of observations and 15
columns of data. The dataset give information by each dumpster from the
three wheels: **Mr. Trash Wheel**, **Professor Trash Wheel**, and
**Gwynns Falls Trash Wheel**. Some of the key variables are
`weight_tons` `plastic_bottles` `cigarette_butts` `glass_bottles` and
`homes_powered`. The total weight of trash collected by Professor Trash
Wheel is 282.26 tons, and the total number of cigarette butts collected
by Gwynnda in June of 2022 is 18120.

## Problem 3

``` r
rent_df = read_csv("data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") |> 
  pivot_longer(cols = 10:125,
               names_to = "date",
               values_to = "rent_rate") |> 
  janitor::clean_names() |> 
  select(-region_type, -state_name, -state, -city, -metro, -region_id, -size_rank) |> 
  rename(zip_code = region_name)
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zip_df = read_csv("data/Zip Codes.csv") |> 
  janitor::clean_names() |> 
  select(-county_code, -county_fips, -state_fips, -file_date, -county)
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
rent_neigh_joint_df = rent_df |> 
  left_join(zip_df, by = c("zip_code")) |> 
  relocate(last_col(), .after = 2)
```

    ## Warning in left_join(rent_df, zip_df, by = c("zip_code")): Detected an unexpected many-to-many relationship between `x` and `y`.
    ## ℹ Row 4757 of `x` matches multiple rows in `y`.
    ## ℹ Row 256 of `y` matches multiple rows in `x`.
    ## ℹ If a many-to-many relationship is expected, set `relationship =
    ##   "many-to-many"` to silence this warning.

The result tidy dataset `rent_neigh_joint_df` has 17516 rows of
observations and 5 columns of data. It contains information of rent by
month throughout 2015 - 2024 in NYC with variables of `zip_code`
`county_name` `neighborhood` `date` and `rent rate`. There are 149
unique zip codes and 43 unique neighborhoods.

``` r
zip_not_app_df = filter(zip_df, !(zip_code %in% rent_df$zip_code)) 
```

There are total 171 zip codes that appear in the ZIP code dataset but
not in the Zillow Rental Price dataset. These zip codes are: 10464,
10474, 10475, 10499, 10550, 10704, 10705, 10803, 11202, 11224, 11239,
11241, 11242, 11243, 11245, 11247, 11251, 11252, 11256, 10008, 10020,
10041, 10043, 10045, 10047, 10048, 10055, 10072, 10080, 10081, 10082,
10087, 10101, 10102, 10103, 10104, 10105, 10106, 10107, 10108, 10109,
10110, 10111, 10112, 10113, 10114, 10115, 10116, 10117, 10118, 10119,
10120, 10121, 10122, 10123, 10124, 10125, 10126, 10129, 10130, 10131,
10132, 10133, 10138, 10149, 10150, 10151, 10152, 10153, 10154, 10155,
10156, 10157, 10158, 10159, 10160, 10161, 10163, 10164, 10165, 10166,
10167, 10168, 10169, 10170, 10171, 10172, 10173, 10174, 10175, 10176,
10177, 10178, 10179, 10185, 10197, 10199, 10213, 10242, 10249, 10256,
10259, 10260, 10261, 10265, 10268, 10269, 10270, 10271, 10272, 10273,
10274, 10275, 10276, 10277, 10278, 10279, 10281, 10285, 10286, 10292,
11001, 11004, 11005, 11040, 11096, 11351, 11352, 11359, 11362, 11363,
11371, 11380, 11381, 11386, 11405, 11411, 11412, 11413, 11414, 11416,
11417, 11419, 11420, 11421, 11422, 11423, 11424, 11425, 11427, 11428,
11429, 11430, 11431, 11433, 11436, 11439, 11451, 11499, 11559, 11580,
11690, 11694, 11695, 11697, 10302, 10307, 10309, 10310, 10311, 10313.

The reason that these zip codes are not included in the Zillow database
could be that there are commercial zip codes with no residential
significance, or retired zip codes. It can also be that the zip code
represents an area with very small populations which does not provide
enough rental data. For example the zip code **10249** in this list is
located in New York, NY, and is a PO-box zip code which does not have
residential housing significance.

``` r
cov19_20vs21_df = filter(
  rent_neigh_joint_df, 
  date == "2020-01-31" | date == "2021-01-31") |> 
  select(zip_code, county_name, neighborhood, rent_rate, date) |> 
  pivot_wider(names_from = date,
              values_from = rent_rate,
              names_prefix = "rent_",
              values_fn = mean,
              values_fill = NA) |> 
  drop_na("rent_2020-01-31","rent_2021-01-31") |> 
  mutate(`rent_2020-01-31` = as.numeric(`rent_2020-01-31`),
         `rent_2021-01-31` = as.numeric(`rent_2021-01-31`)) |> 
  mutate(price_dropped = `rent_2020-01-31` - `rent_2021-01-31`)
```

``` r
top_drop = arrange(cov19_20vs21_df, desc(price_dropped)) |> 
  slice_head(n = 10) |> 
  select(zip_code, county_name, neighborhood,price_dropped) |> 
  kable(
    digits = 0,
    col.name = c("zip_code","borough","neighborhood","price_dropped")
  )
top_drop
```

| zip_code | borough         | neighborhood                  | price_dropped |
|---------:|:----------------|:------------------------------|--------------:|
|    10007 | New York County | Lower Manhattan               |           913 |
|    10069 | New York County | NA                            |           748 |
|    10009 | New York County | Lower East Side               |           714 |
|    10016 | New York County | Gramercy Park and Murray Hill |           712 |
|    10001 | New York County | Chelsea and Clinton           |           710 |
|    10002 | New York County | Lower East Side               |           710 |
|    10004 | New York County | Lower Manhattan               |           706 |
|    10038 | New York County | Lower Manhattan               |           698 |
|    10012 | New York County | Greenwich Village and Soho    |           686 |
|    10010 | New York County | Gramercy Park and Murray Hill |           685 |

The table above shows the 10 zip codes that experienced the largest rent
drop from Jan 2020 to Jan 2021 due to the impact of covid-19. The
relevant borough name and neighborhood are also displayed in the table.
All these zip codes are in New York county, indicating that the most
populated area also experienced the largest impact of covid in terms of
rent.
